# Generated by Django 2.2.2 on 2019-11-03 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(blank=True, upload_to='')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.CharField(max_length=100)),
                ('product_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-product_date',),
            },
        ),
    ]
