# Generated by Django 2.2.2 on 2019-11-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_chosen',
            field=models.CharField(choices=[('ORDER PLACE', 'ORDER PLACE'), ('ON THE WAY', 'ON THE WAY'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('PROCESS COMPLETE', 'PROCESS COMPLETE')], default='ORDER PLACED', max_length=1),
            preserve_default=False,
        ),
    ]
