# Generated by Django 2.2.2 on 2019-11-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_chosen',
            field=models.CharField(choices=[('ORDER PLACE', 'ORDER PLACE'), ('ON THE WAY', 'ON THE WAY'), ('DELIVERED', 'DELIVERED'), ('RETURNED', 'RETURNED'), ('PROCESS COMPLETE', 'PROCESS COMPLETE')], max_length=20),
        ),
    ]
