# Generated by Django 2.2.6 on 2019-11-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_chosen',
            field=models.CharField(choices=[('1', 'ORDER PLACE'), ('2', 'ON THE WAY'), ('3', 'DELIVERED'), ('4', 'RETURNED'), ('5', 'PROCESS COMPLETE')], max_length=20),
        ),
    ]
