# Generated by Django 2.2.6 on 2019-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_chosen',
            field=models.CharField(choices=[('1', 'ORDER PLACE'), ('2', 'ON THE WAY'), ('3', 'DELIVERED'), ('4', 'RETURNED'), ('5', 'PROCESS COMPLETE')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=1000),
        ),
    ]
